services:
  db_students:
    image: postgres
    container_name: db_students
    restart: always
    ports:
      - 4321:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

  node_app_students:
    container_name: node_app_students
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db_students
    env_file:
      - .env

volumes:
  postgres:
